1. Data cleaning 

2. splitting the train and test data

3. Applying the BagOfWords

4. Apply the machine learning algorithm to predict the data


In [1]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
import  re


Data Extraction

In [26]:
df = pd.read_csv(filepath_or_buffer='SMSSpamCollection.txt',sep='\t',names=['label','messaage'])

df.head(5)

label                                           messaage
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

Data cleaning and preprocessing


preprocessing include the removal of unneccesary words in vocabulary based ont he stop words

In [9]:
ps = PorterStemmer()

corpus:list = []
for i in range(0,len(df)):
    sentence = re.sub('[^a-zA-Z]', ' ', df.iloc[i]['messaage'])
    words :list = sentence.split()
    words = [ps.stem(word=word) for word in words if word not in stopwords.words('english') ] 
    sentence =' '.join(words)
    corpus.append(sentence)
    
    

In [10]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate t c appli',
 'u dun say earli hor u c alreadi say',
 'nah i think goe usf live around though',
 'freemsg hey darl week word back i like fun still tb ok xxx std chg send rcv',
 'even brother like speak they treat like aid patent',
 'as per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner as valu network custom select receivea prize reward to claim call claim code kl valid hour',
 'had mobil month u r entitl updat latest colour mobil camera free call the mobil updat co free',
 'i gonna home soon want talk stuff anymor tonight k i cri enough today',
 'six chanc win cash from pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent you week free membership prize jackpot txt word claim no t c www dbuk net lccltd pobo

In [11]:
len(corpus)

5572

In [12]:
Y = df['label'].values

In [29]:
Y = pd.get_dummies(df['label'])


In [31]:
y=Y.iloc[:,0].values

In [36]:
y

array([ True,  True, False, ...,  True,  True,  True], shape=(5572,))

In [41]:
import numpy as np
y=np.where(y,1,0)
print(y)

[1 1 0 ... 1 1 1]


Spilt the train and test data 

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(corpus,y,test_size=0.2)

In [43]:
Y_train

array([1, 1, 1, ..., 0, 0, 1], shape=(4457,))

In [44]:
X_train


['k come nordstrom done',
 'no thank you wonder',
 'oh ok prob',
 'hi you spoke maneesha v we like know satisfi experi repli toll free ye no',
 'id check like bowl worth left',
 'congrat year special cinema pass call c suprman v matrix starwar etc free bx ip pm dont miss',
 'hello damn christma thing i think decid keep mp doesnt work',
 'have finish work yet',
 'that mean get door',
 'oh gei that happend tron mayb ill dl',
 'here got ur favorit oyster n got favorit sashimi ok lar dun say alreadi wait ur stomach start rumbl',
 'i sent do like',
 'a boy late home hi father power of frndship',
 'smsservic yourinclus text credit pl goto www comuk net login qxj unsubscrib stop extra charg help comuk cm ae',
 'no need buy lunch i eat maggi mee',
 'got thing may pub later',
 'thank rington order refer number x your mobil charg should tone arriv pleas call custom servic',
 'i wish thing differ i wonder abl show much valu pl continu brisk walk drug without askin pleas find thing laugh i love de

Apply BagOfWords and fetch the features


Covert the data into metrix 

In [47]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=1000,binary=True,ngram_range=(2,2))
X=cv.fit_transform(X_train).toarray()
X_test=cv.transform(X_test).toarray()

In [52]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 1000))

In [48]:
cv.vocabulary_

{'oh ok': np.int64(592),
 'hi you': np.int64(368),
 'spoke maneesha': np.int64(750),
 'maneesha we': np.int64(491),
 'like know': np.int64(455),
 'toll free': np.int64(826),
 'ye no': np.int64(972),
 'bx ip': np.int64(59),
 'ip pm': np.int64(401),
 'dont miss': np.int64(202),
 'ok lar': np.int64(593),
 'do like': np.int64(194),
 'text credit': np.int64(781),
 'credit pl': np.int64(165),
 'www comuk': np.int64(965),
 'comuk net': np.int64(142),
 'net login': np.int64(551),
 'unsubscrib stop': np.int64(856),
 'stop extra': np.int64(757),
 'extra charg': np.int64(224),
 'charg help': np.int64(117),
 'no need': np.int64(565),
 'thank rington': np.int64(791),
 'rington order': np.int64(680),
 'order refer': np.int64(608),
 'number your': np.int64(588),
 'your mobil': np.int64(999),
 'mobil charg': np.int64(519),
 'charg should': np.int64(118),
 'should tone': np.int64(719),
 'tone arriv': np.int64(829),
 'arriv pleas': np.int64(22),
 'pleas call': np.int64(632),
 'call custom': np.int64(69)

In [49]:
from sklearn.naive_bayes import  MultinomialNB
mnb = MultinomialNB()
mnb.fit(X=X,y=Y_train)


MultinomialNB()

In [50]:
Y_pred = mnb.predict(X_test)

/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b


check the peformance and accuracy of the model

In [51]:
from sklearn.metrics import accuracy_score,classification_report

print('accuracy_score : ',accuracy_score(y_true=Y_test,y_pred=Y_pred))
print('classification report :',classification_report(y_true=Y_test,y_pred=Y_pred))

accuracy_score :  0.9605381165919282
classification report :               precision    recall  f1-score   support

           0       0.99      0.73      0.84       158
           1       0.96      1.00      0.98       957

    accuracy                           0.96      1115
   macro avg       0.97      0.86      0.91      1115
weighted avg       0.96      0.96      0.96      1115

